apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer2
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer2
  chart:
    git: https://github.com/balajihub/blockchain-automation-framework.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer2
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://acab3c720472246519b96cb01adcfe82-1250505999.us-east-2.elb.amazonaws.com
      role: vault-role
      authpath: dev2supplychain-net-auth
      secretprefix: secret/crypto/ordererOrganizations/supplychain-net/orderers/orderer2.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: haproxy
      external_url_suffix: fabrictest.hyperrnd.com

    genesis: |-
      CiIaIC9lVhsPJg8xJSRfqil0zPwJ48/Tv9HMDeeRwzJzywrhErFXCq5XCqtXCngKWggBEAEaBgj9
      z7OJBiIKc3lzY2hhbm5lbCpAMjQ5YjdkMWMyMGE4OWUwYjlhYTgxNGJlZjliNTkwYTEwODBlNzcy
      ZDczZWMyMzNjNDhkZjkxYjgyNTgzNzAyNBIaEhhTXsWWMvkxcaqovUTehUkR7b2xyJLmWQ4SrlYK
      q1YSqFYSu1EKB09yZGVyZXISr1ES1BcKDnN1cHBseWNoYWluTVNQEsEXGs0VCgNNU1ASxRUSuhUS
      txUKDnN1cHBseWNoYWluTVNQEqYGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNKVEND
      QWN1Z0F3SUJBZ0lKQU9LSWJ2WHFha0phTUFvR0NDcUdTTTQ5QkFNQ01IWXhDekFKQmdOVkJBWVQK
      QWtkQ01ROHdEUVlEVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdB
      MVVFQ2d3SApUM0prWlhKbGNqRXpNREVHQTFVRUF3d3FZMkV1YzNWd2NHeDVZMmhoYVc0dGJtVjBM
      bVpoWW5KcFkzUmxjM1F1CmFIbHdaWEp5Ym1RdVkyOXRNQjRYRFRJeE1EZ3pNREUwTVRBek4xb1hE
      VEkwTURZeE9URTBNVEF6TjFvd2RqRUwKTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZi
      bVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1TVJBdwpEZ1lEVlFRS0RBZFBjbVJsY21WeU1UTXdN
      UVlEVlFRRERDcGpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXVabUZpCmNtbGpkR1Z6ZEM1b2VYQmxj
      bkp1WkM1amIyMHdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBVGMKMlhseW04NDZ4
      cVhzMklXc2t5dE5DZ0xub2NjeXdiS2NEVGx3MEprRUwrZEQ1REtlK05KTGVKL2M0UTJBWFhkWApl
      cERVRkt0U1dJaVl0RUVqSHNMcm8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3
      RUIvd1FFCkF3SUJwakFkQmdOVkhRNEVGZ1FVTDlKNm1RQnRpd01INFN4QXI1cG00a2NSSEswd0Nn
      WUlLb1pJemowRUF3SUQKU0FBd1JRSWhBTEhaQS9qQWZielBWUEtOdU54Q2JiVkV2dTZZL09SQnBu
      Y0Y0cjRHTGNXVUFpQkc0M2J5T1RrcgpLTlZaN0loU2oxb2h5NGpYUkMveDFtT0pXRkVzZngxN3Fn
      PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoiwggtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0t
      LS0KTUlJQytUQ0NBcUNnQXdJQkFnSVVSMisxdUJQNnBXNE92Z1JyUHpwWEpMSysra1V3Q2dZSUtv
      Wkl6ajBFQXdJdwpkakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1B
      MEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1UTXdNUVlEVlFRRERD
      cGpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXUKWm1GaWNtbGpkR1Z6ZEM1b2VYQmxjbkp1WkM1amIy
      MHdIaGNOTWpFd09ETXdNVFF4TURBd1doY05Nakl3T0RNdwpNVFF4TlRBd1dqQnNNUXN3Q1FZRFZR
      UUdFd0pIUWpFYk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1ClpHOXVNUkF3RGdZRFZR
      UUtFd2RQY21SbGNtVnlNUTR3REFZRFZRUUxFd1ZoWkcxcGJqRWVNQndHQTFVRUF3d1YKUVdSdGFX
      NUFjM1Z3Y0d4NVkyaGhhVzR0Ym1WME1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdB
      RQpoZjhCUHBPMFFtbWo0UWJuUDZkZk5CTEtnYnhVY1FzRm9CT25DVmR4dW56N0RuNlBDMjZqcjhU
      UE12Lzk2QVkyCkh3T2tKUjl1dThzS1JQL2pXb1BZcnFPQ0FSUXdnZ0VRTUE0R0ExVWREd0VCL3dR
      RUF3SUhnREFNQmdOVkhSTUIKQWY4RUFqQUFNQjBHQTFVZERnUVdCQlI4VGgyMWEwUnE3Q01XeTBK
      YnpOZmtTUXpLbkRBZkJnTlZIU01FR0RBVwpnQlF2MG5xWkFHMkxBd2ZoTEVDdm1tYmlSeEVjclRB
      a0JnTlZIUkVFSFRBYmdobGpZUzEwYjI5c2N5MDNPRGRpCk5HWTVabU5rTFhOeE5HMDBNSUdKQmdn
      cUF3UUZCZ2NJQVFSOWV5SmhkSFJ5Y3lJNmV5SmhZbUZqTG1sdWFYUWkKT2lKMGNuVmxJaXdpWVdS
      dGFXNGlPaUowY25WbElpd2lhR1l1UVdabWFXeHBZWFJwYjI0aU9pSWlMQ0pvWmk1Rgpibkp2Ykd4
      dFpXNTBTVVFpT2lKQlpHMXBia0J6ZFhCd2JIbGphR0ZwYmkxdVpYUWlMQ0pvWmk1VWVYQmxJam9p
      CllXUnRhVzRpZlgwd0NnWUlLb1pJemowRUF3SURSd0F3UkFJZ1hjeU5WVy9lNTg5WXl4SjBkanhm
      UmY2dkJ0NGIKUTVwdDUzeGFlZ3Nid2prQ0lCQ3pxVjV2TG14QkR5Q0VpRk9hY1ZnalRKMUNCTU8x
      YVAvZDVaYjJkVzBICi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1Nkqm
      Bi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDSlRDQ0FjdWdBd0lCQWdJSkFPS0lidlhx
      YWtKYU1Bb0dDQ3FHU000OUJBTUNNSFl4Q3pBSkJnTlZCQVlUCkFrZENNUTh3RFFZRFZRUUlEQVpN
      YjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0gKVDNKa1pYSmxjakV6
      TURFR0ExVUVBd3dxWTJFdWMzVndjR3g1WTJoaGFXNHRibVYwTG1aaFluSnBZM1JsYzNRdQphSGx3
      WlhKeWJtUXVZMjl0TUI0WERUSXhNRGd6TURFME1UQXpOMW9YRFRJME1EWXhPVEUwTVRBek4xb3dk
      akVMCk1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dU1SQXcKRGdZRFZRUUtEQWRQY21SbGNtVnlNVE13TVFZRFZRUUREQ3BqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF1Wm1GaQpjbWxqZEdWemRDNW9lWEJsY25KdVpDNWpiMjB3V1RBVEJnY3Fo
      a2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVRjCjJYbHltODQ2eHFYczJJV3NreXROQ2dMbm9jY3l3
      YktjRFRsdzBKa0VMK2RENURLZStOSkxlSi9jNFEyQVhYZFgKZXBEVUZLdFNXSWlZdEVFakhzTHJv
      MEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VCL3dRRQpBd0lCcGpBZEJnTlZI
      UTRFRmdRVUw5SjZtUUJ0aXdNSDRTeEFyNXBtNGtjUkhLMHdDZ1lJS29aSXpqMEVBd0lEClNBQXdS
      UUloQUxIWkEvakFmYnpQVlBLTnVOeENiYlZFdnU2WS9PUkJwbmNGNHI0R0xjV1VBaUJHNDNieU9U
      a3IKS05WWjdJaFNqMW9oeTRqWFJDL3gxbU9KV0ZFc2Z4MTdxZz09Ci0tLS0tRU5EIENFUlRJRklD
      QVRFLS0tLS0KGgZBZG1pbnMiNwoHV3JpdGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBs
      eWNoYWluTVNQGgZBZG1pbnMiOAoGQWRtaW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5
      Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0VuZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoO
      c3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3CgdSZWFkZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoO
      c3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoGQWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICA
      QBoGQWRtaW5zGh4KDEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3Ry
      aWN0aW9ucxIIGgZBZG1pbnMaJAoMQ2FwYWJpbGl0aWVzEhQSCgoICgRWMl8wEgAaBkFkbWlucxqq
      NwoNQ29uc2Vuc3VzVHlwZRKYNxKNNwoIZXRjZHJhZnQSgDcKoRIKIG9yZGVyZXIxLmZhYnJpY3Rl
      c3QuaHlwZXJybmQuY29tEPtBGvsILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVEND
      QXNlZ0F3SUJBZ0lVSGFZWVlqUTVieG1BekpqMWR1VVlTS0JFcVNrd0NnWUlLb1pJemowRUF3SXcK
      ZGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNVE13TVFZRFZRUUREQ3BqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF1ClptRmljbWxqZEdWemRDNW9lWEJsY25KdVpDNWpiMjB3SGhjTk1qRXdP
      RE13TVRReE1EQXdXaGNOTWpJd09ETXcKTVRReE5UQXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWJN
      QmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dQpaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxj
      bVZ5TVJBd0RnWURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFECkV4aHZjbVJsY21WeU1TNXpk
      WEJ3YkhsamFHRnBiaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUIKQndOQ0FBUVJv
      UEVJZW5peFllbnlnVVFXWlpMbFI5cmtYbjdSemZ3Mjc5c3pnMER0dWUyc0tkZnoxdlRobWhYYgpO
      VFBsSDhybXNmanJqUHRqVzk1V1lPa0taMUUrbzRJQk5qQ0NBVEl3RGdZRFZSMFBBUUgvQkFRREFn
      T29NQjBHCkExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQU1CZ05WSFJNQkFm
      OEVBakFBTUIwR0ExVWQKRGdRV0JCVE1GZEowbWtpdnIvQi9wemtuTVV3NXROd290akFmQmdOVkhT
      TUVHREFXZ0JRdjBucVpBRzJMQXdmaApMRUN2bW1iaVJ4RWNyVEJGQmdOVkhSRUVQakE4Z2hodmNt
      UmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFNDCklHOXlaR1Z5WlhJeExtWmhZbkpwWTNSbGMz
      UXVhSGx3WlhKeWJtUXVZMjl0TUd3R0NDb0RCQVVHQndnQkJHQjcKSW1GMGRISnpJanA3SW1obUxr
      Rm1abWxzYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaQpiM0prWlhKbGNq
      RXVjM1Z3Y0d4NVkyaGhhVzR0Ym1WMElpd2lhR1l1Vkhsd1pTSTZJbTl5WkdWeVpYSWlmWDB3CkNn
      WUlLb1pJemowRUF3SURTQUF3UlFJaEFKRWNVL0F4alRwb1NWaStSL05KUGszU1hMcklFZkZvc3R1
      OWw0a3gKbmxJWUFpQjJkV2hYSTBKaVZPWkxoZm1yMGZjMitlbmt1clVrV20rUVRxcGgxMjlNbnc9
      PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiL7CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0t
      LQpNSUlESVRDQ0FzZWdBd0lCQWdJVUhhWVlZalE1YnhtQXpKajFkdVVZU0tCRXFTa3dDZ1lJS29a
      SXpqMEVBd0l3CmRqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEw
      R0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVRNd01RWURWUVFERENw
      allTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdQpabUZpY21samRHVnpkQzVvZVhCbGNuSnVaQzVqYjIw
      d0hoY05NakV3T0RNd01UUXhNREF3V2hjTk1qSXdPRE13Ck1UUXhOVEF3V2pCeE1Rc3dDUVlEVlFR
      R0V3SkhRakViTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXUKWkc5dU1SQXdEZ1lEVlFR
      S0V3ZFBjbVJsY21WeU1SQXdEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRRApFeGh2Y21S
      bGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1C
      CkJ3TkNBQVFSb1BFSWVuaXhZZW55Z1VRV1paTGxSOXJrWG43UnpmdzI3OXN6ZzBEdHVlMnNLZGZ6
      MXZUaG1oWGIKTlRQbEg4cm1zZmpyalB0alc5NVdZT2tLWjFFK280SUJOakNDQVRJd0RnWURWUjBQ
      QVFIL0JBUURBZ09vTUIwRwpBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFN
      QmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkCkRnUVdCQlRNRmRKMG1raXZyL0IvcHprbk1VdzV0Tndv
      dGpBZkJnTlZIU01FR0RBV2dCUXYwbnFaQUcyTEF3ZmgKTEVDdm1tYmlSeEVjclRCRkJnTlZIUkVF
      UGpBOGdoaHZjbVJsY21WeU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhTQwpJRzl5WkdWeVpYSXhMbVpo
      WW5KcFkzUmxjM1F1YUhsd1pYSnlibVF1WTI5dE1Hd0dDQ29EQkFVR0J3Z0JCR0I3CkltRjBkSEp6
      SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2kK
      YjNKa1pYSmxjakV1YzNWd2NHeDVZMmhoYVc0dGJtVjBJaXdpYUdZdVZIbHdaU0k2SW05eVpHVnla
      WElpZlgwdwpDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBSkVjVS9BeGpUcG9TVmkrUi9OSlBrM1NY
      THJJRWZGb3N0dTlsNGt4Cm5sSVlBaUIyZFdoWEkwSmlWT1pMaGZtcjBmYzIrZW5rdXJVa1dtK1FU
      cXBoMTI5TW53PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoKoRIKIG9yZGVyZXIyLmZhYnJp
      Y3Rlc3QuaHlwZXJybmQuY29tEPtBGvsILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJ
      VENDQXNlZ0F3SUJBZ0lVU1pqNExQQTlSejI1WWxjYjYwNnI1Y1AwTzdNd0NnWUlLb1pJemowRUF3
      SXcKZGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3
      d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNVE13TVFZRFZRUUREQ3BqWVM1emRY
      QndiSGxqYUdGcGJpMXVaWFF1ClptRmljbWxqZEdWemRDNW9lWEJsY25KdVpDNWpiMjB3SGhjTk1q
      RXdPRE13TVRReE1EQXdXaGNOTWpJd09ETXcKTVRReE5UQXdXakJ4TVFzd0NRWURWUVFHRXdKSFFq
      RWJNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dQpaRzl1TVJBd0RnWURWUVFLRXdkUGNt
      UmxjbVZ5TVJBd0RnWURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFECkV4aHZjbVJsY21WeU1p
      NXpkWEJ3YkhsamFHRnBiaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUIKQndOQ0FB
      VGJEVHBmTXdDc01tWWFIWFNpNEQ0RlZWR3gwdzkzenFPR2V5a1QzSkZDVkVwZ0pTR0h6M2FpRjZ5
      MQpFdkxDaWMzV0t0S2FjZ3pzVWwxUVNjN3NiQ3BlbzRJQk5qQ0NBVEl3RGdZRFZSMFBBUUgvQkFR
      REFnT29NQjBHCkExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQU1CZ05WSFJN
      QkFmOEVBakFBTUIwR0ExVWQKRGdRV0JCUUhZcm4vZ3pmM3JCN0pwZ0lPZU54aGx4YnlLREFmQmdO
      VkhTTUVHREFXZ0JRdjBucVpBRzJMQXdmaApMRUN2bW1iaVJ4RWNyVEJGQmdOVkhSRUVQakE4Z2ho
      dmNtUmxjbVZ5TWk1emRYQndiSGxqYUdGcGJpMXVaWFNDCklHOXlaR1Z5WlhJeUxtWmhZbkpwWTNS
      bGMzUXVhSGx3WlhKeWJtUXVZMjl0TUd3R0NDb0RCQVVHQndnQkJHQjcKSW1GMGRISnpJanA3SW1o
      bUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaQpiM0prWlhK
      bGNqSXVjM1Z3Y0d4NVkyaGhhVzR0Ym1WMElpd2lhR1l1Vkhsd1pTSTZJbTl5WkdWeVpYSWlmWDB3
      CkNnWUlLb1pJemowRUF3SURTQUF3UlFJaEFMdklUb1ZNNWI2VWZscDBUM1ZWNmFwOWRrRkE1NkdM
      cFpoOGVzMVAKVGc0N0FpQmxvcXRsMXYwOFR5S0ZtOVdkeHZEOGhDWFdjdk9nVExabDNLdXVRRTZq
      blE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiL7CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlESVRDQ0FzZWdBd0lCQWdJVVNaajRMUEE5UnoyNVlsY2I2MDZyNWNQME83TXdDZ1lJ
      S29aSXpqMEVBd0l3CmRqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVRNd01RWURWUVFE
      RENwallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdQpabUZpY21samRHVnpkQzVvZVhCbGNuSnVaQzVq
      YjIwd0hoY05NakV3T0RNd01UUXhNREF3V2hjTk1qSXdPRE13Ck1UUXhOVEF3V2pCeE1Rc3dDUVlE
      VlFRR0V3SkhRakViTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXUKWkc5dU1SQXdEZ1lE
      VlFRS0V3ZFBjbVJsY21WeU1SQXdEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRRApFeGh2
      Y21SbGNtVnlNaTV6ZFhCd2JIbGphR0ZwYmkxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9Q
      UU1CCkJ3TkNBQVRiRFRwZk13Q3NNbVlhSFhTaTRENEZWVkd4MHc5M3pxT0dleWtUM0pGQ1ZFcGdK
      U0dIejNhaUY2eTEKRXZMQ2ljM1dLdEthY2d6c1VsMVFTYzdzYkNwZW80SUJOakNDQVRJd0RnWURW
      UjBQQVFIL0JBUURBZ09vTUIwRwpBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0RB
      akFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkCkRnUVdCQlFIWXJuL2d6ZjNyQjdKcGdJT2VOeGhs
      eGJ5S0RBZkJnTlZIU01FR0RBV2dCUXYwbnFaQUcyTEF3ZmgKTEVDdm1tYmlSeEVjclRCRkJnTlZI
      UkVFUGpBOGdoaHZjbVJsY21WeU1pNXpkWEJ3YkhsamFHRnBiaTF1WlhTQwpJRzl5WkdWeVpYSXlM
      bVpoWW5KcFkzUmxjM1F1YUhsd1pYSnlibVF1WTI5dE1Hd0dDQ29EQkFVR0J3Z0JCR0I3CkltRjBk
      SEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlq
      b2kKYjNKa1pYSmxjakl1YzNWd2NHeDVZMmhoYVc0dGJtVjBJaXdpYUdZdVZIbHdaU0k2SW05eVpH
      VnlaWElpZlgwdwpDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBTHZJVG9WTTViNlVmbHAwVDNWVjZh
      cDlka0ZBNTZHTHBaaDhlczFQClRnNDdBaUJsb3F0bDF2MDhUeUtGbTlXZHh2RDhoQ1hXY3ZPZ1RM
      WmwzS3V1UUU2am5RPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoKoRIKIG9yZGVyZXIzLmZh
      YnJpY3Rlc3QuaHlwZXJybmQuY29tEPtBGvsILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1J
      SURJVENDQXNlZ0F3SUJBZ0lVVnRreHh6WjlHVW1ueE1SZEJpQjZRdTVxQ1h3d0NnWUlLb1pJemow
      RUF3SXcKZGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFV
      RUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNVE13TVFZRFZRUUREQ3BqWVM1
      emRYQndiSGxqYUdGcGJpMXVaWFF1ClptRmljbWxqZEdWemRDNW9lWEJsY25KdVpDNWpiMjB3SGhj
      Tk1qRXdPRE13TVRReE1EQXdXaGNOTWpJd09ETXcKTVRReE5UQXdXakJ4TVFzd0NRWURWUVFHRXdK
      SFFqRWJNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dQpaRzl1TVJBd0RnWURWUVFLRXdk
      UGNtUmxjbVZ5TVJBd0RnWURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFECkV4aHZjbVJsY21W
      eU15NXpkWEJ3YkhsamFHRnBiaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUIKQndO
      Q0FBVGRLbThlWnVlR29YTmg2OWxLeGpvdXI5ZW9qcUMyd2hBKzhFTmJaMUhnbDhsZ1ZKU0wzNXNT
      bTBvaQpTeWJaQVVnUUNnWkRuckR0U2JsNnJycmlvQS8wbzRJQk5qQ0NBVEl3RGdZRFZSMFBBUUgv
      QkFRREFnT29NQjBHCkExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQU1CZ05W
      SFJNQkFmOEVBakFBTUIwR0ExVWQKRGdRV0JCVEJiY1lwWUI5alpUdkJjNUY3b1FvUnR1T2VEREFm
      QmdOVkhTTUVHREFXZ0JRdjBucVpBRzJMQXdmaApMRUN2bW1iaVJ4RWNyVEJGQmdOVkhSRUVQakE4
      Z2hodmNtUmxjbVZ5TXk1emRYQndiSGxqYUdGcGJpMXVaWFNDCklHOXlaR1Z5WlhJekxtWmhZbkpw
      WTNSbGMzUXVhSGx3WlhKeWJtUXVZMjl0TUd3R0NDb0RCQVVHQndnQkJHQjcKSW1GMGRISnpJanA3
      SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaQpiM0pr
      WlhKbGNqTXVjM1Z3Y0d4NVkyaGhhVzR0Ym1WMElpd2lhR1l1Vkhsd1pTSTZJbTl5WkdWeVpYSWlm
      WDB3CkNnWUlLb1pJemowRUF3SURTQUF3UlFJaEFNdGhwcnhCMk1sWjhnZ1hUdURHTFFmaWdFaVBZ
      L1dpVDQ2bkx0ZXkKbU1UbUFpQkZjaFA2OURycDZSQmNsN3NydlRMRmhSSDR0R2llTWZBMG9vTU9a
      dy9oUkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiL7CC0tLS0tQkVHSU4gQ0VSVElGSUNB
      VEUtLS0tLQpNSUlESVRDQ0FzZWdBd0lCQWdJVVZ0a3h4elo5R1VtbnhNUmRCaUI2UXU1cUNYd3dD
      Z1lJS29aSXpqMEVBd0l3CmRqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZi
      akVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVRNd01RWURW
      UVFERENwallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdQpabUZpY21samRHVnpkQzVvZVhCbGNuSnVa
      QzVqYjIwd0hoY05NakV3T0RNd01UUXhNREF3V2hjTk1qSXdPRE13Ck1UUXhOVEF3V2pCeE1Rc3dD
      UVlEVlFRR0V3SkhRakViTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXUKWkc5dU1SQXdE
      Z1lEVlFRS0V3ZFBjbVJsY21WeU1SQXdEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRRApF
      eGh2Y21SbGNtVnlNeTV6ZFhCd2JIbGphR0ZwYmkxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhr
      ak9QUU1CCkJ3TkNBQVRkS204ZVp1ZUdvWE5oNjlsS3hqb3VyOWVvanFDMndoQSs4RU5iWjFIZ2w4
      bGdWSlNMMzVzU20wb2kKU3liWkFVZ1FDZ1pEbnJEdFNibDZycnJpb0EvMG80SUJOakNDQVRJd0Rn
      WURWUjBQQVFIL0JBUURBZ09vTUIwRwpBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJR
      Y0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkCkRnUVdCQlRCYmNZcFlCOWpaVHZCYzVGN29R
      b1J0dU9lRERBZkJnTlZIU01FR0RBV2dCUXYwbnFaQUcyTEF3ZmgKTEVDdm1tYmlSeEVjclRCRkJn
      TlZIUkVFUGpBOGdoaHZjbVJsY21WeU15NXpkWEJ3YkhsamFHRnBiaTF1WlhTQwpJRzl5WkdWeVpY
      SXpMbVpoWW5KcFkzUmxjM1F1YUhsd1pYSnlibVF1WTI5dE1Hd0dDQ29EQkFVR0J3Z0JCR0I3Cklt
      RjBkSEp6SWpwN0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVs
      RUlqb2kKYjNKa1pYSmxjak11YzNWd2NHeDVZMmhoYVc0dGJtVjBJaXdpYUdZdVZIbHdaU0k2SW05
      eVpHVnlaWElpZlgwdwpDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBTXRocHJ4QjJNbFo4Z2dYVHVE
      R0xRZmlnRWlQWS9XaVQ0Nm5MdGV5Cm1NVG1BaUJGY2hQNjlEcnA2UkJjbDdzcnZUTEZoUkg0dEdp
      ZU1mQTBvb01PWncvaFJBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoSEgoFNTAwbXMQChgB
      IAUogICACBoGQWRtaW5zIioKD0Jsb2NrVmFsaWRhdGlvbhIXEg0IAxIJCgdXcml0ZXJzGgZBZG1p
      bnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJ
      CgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMqBkFk
      bWlucxLOAQoLQ29uc29ydGl1bXMSvgESdAoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtElsaQAoVQ2hh
      bm5lbENyZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1p
      bnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5u
      ZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKEEhhc2hpbmdBbGdv
      cml0aG0SEhIICgZTSEEyNTYaBkFkbWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhAS
      Bgj/////DxoGQWRtaW5zGqUBChBPcmRlcmVyQWRkcmVzc2VzEpABEnUKJW9yZGVyZXIxLmZhYnJp
      Y3Rlc3QuaHlwZXJybmQuY29tOjg0NDMKJW9yZGVyZXIyLmZhYnJpY3Rlc3QuaHlwZXJybmQuY29t
      Ojg0NDMKJW9yZGVyZXIzLmZhYnJpY3Rlc3QuaHlwZXJybmQuY29tOjg0NDMaFy9DaGFubmVsL09y
      ZGVyZXIvQWRtaW5zGiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMiIgoHUmVh
      ZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJz
      GgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMqBkFkbWlucxoOCgQK
      AgoACgAKAAoACgA=
