apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer3
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer3
  chart:
    git: https://github.com/balajihub/blockchain-automation-framework.git
    ref: main
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer3
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://acab3c720472246519b96cb01adcfe82-1250505999.us-east-2.elb.amazonaws.com
      role: vault-role
      authpath: dev2supplychain-net-auth
      secretprefix: secret/crypto/ordererOrganizations/supplychain-net/orderers/orderer3.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: haproxy
      external_url_suffix: fabrictest.hyperrnd.com

    genesis: |-
      CiIaIB9iumn5AzwSxdP4UFjBoiGINiA/KPXQ6mKVoZKlO8R1EqBXCp1XCppXCngKWggBEAEaBgj/
      g7SJBiIKc3lzY2hhbm5lbCpANDkyMTU5YzFmOGE0NzIxYjkyMWJmNmQ1Yzk3ZTAwMjNiYTY4ZTVl
      NzUzY2FmYzk4OTljZjc0OTQwNDliMWRiMhIaEhgjXkbka92ZFw9gnTOrU2IYidoFnSJjtzkSnVYK
      mlYSl1YSqlEKB09yZGVyZXISnlES0RcKDnN1cHBseWNoYWluTVNQEr4XGsoVCgNNU1ASwhUStxUS
      tBUKDnN1cHBseWNoYWluTVNQEqUGLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNKakND
      QWN1Z0F3SUJBZ0lKQUp2RUdBU3ZTMDRuTUFvR0NDcUdTTTQ5QkFNQ01IWXhDekFKQmdOVkJBWVQK
      QWtkQ01ROHdEUVlEVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdB
      MVVFQ2d3SApUM0prWlhKbGNqRXpNREVHQTFVRUF3d3FZMkV1YzNWd2NHeDVZMmhoYVc0dGJtVjBM
      bVpoWW5KcFkzUmxjM1F1CmFIbHdaWEp5Ym1RdVkyOXRNQjRYRFRJeE1EZ3pNREUwTlRBd01sb1hE
      VEkwTURZeE9URTBOVEF3TWxvd2RqRUwKTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZi
      bVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1TVJBdwpEZ1lEVlFRS0RBZFBjbVJsY21WeU1UTXdN
      UVlEVlFRRERDcGpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXVabUZpCmNtbGpkR1Z6ZEM1b2VYQmxj
      bkp1WkM1amIyMHdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBU3MKemx5R0Q2Sksy
      M2xHaGR6R0lvZWlEdDFtQlVBRkZ1S2g5c1NwVzRWWWxTYm82YUpQRitBcWxmM1owcVgzZHZKLwpK
      NC9acVYzbTBtYnRvQW9kL3lQMW8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3
      RUIvd1FFCkF3SUJwakFkQmdOVkhRNEVGZ1FVZkdTRDBRaUNDZEtmcXRFaWJtby9MV3BvV0Jzd0Nn
      WUlLb1pJemowRUF3SUQKU1FBd1JnSWhBS1Y5eGdhRW5kWUJMZXpRK1plVDV6elRKV2kxUjBBcjZn
      K1RRTURSVnprcUFpRUEwaTA4MXJmegptWEJoYnZESlRnU3hYN1NzN1dkN3d0d3VoV29pTXl3T1Zi
      VT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLSLBCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0t
      LQpNSUlDK1RDQ0FxQ2dBd0lCQWdJVVFjRGs0ZzNvMEJXZlVLUjRnRHZPdmgxSzMva3dDZ1lJS29a
      SXpqMEVBd0l3CmRqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEw
      R0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVRNd01RWURWUVFERENw
      allTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdQpabUZpY21samRHVnpkQzVvZVhCbGNuSnVaQzVqYjIw
      d0hoY05NakV3T0RNd01UUTFNekF3V2hjTk1qSXdPRE13Ck1UUTFPREF3V2pCc01Rc3dDUVlEVlFR
      R0V3SkhRakViTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXUKWkc5dU1SQXdEZ1lEVlFR
      S0V3ZFBjbVJsY21WeU1RNHdEQVlEVlFRTEV3VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VgpRV1J0YVc1
      QWMzVndjR3g1WTJoaGFXNHRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FF
      ClVMMFIwOGhET0NXaFhPek1jMWZZY04wWmFtNzJrRWdnYlBGMjdUREMwdEs1dXhuZjU4YUQ2OFZY
      b1FXSWdYcG4KdG5Xam9hd25sVzBoZlZLc2lIVWdGYU9DQVJRd2dnRVFNQTRHQTFVZER3RUIvd1FF
      QXdJSGdEQU1CZ05WSFJNQgpBZjhFQWpBQU1CMEdBMVVkRGdRV0JCVElwUEUzR3pwNzlLMGdhRCta
      WGdGeHB2TlY1VEFmQmdOVkhTTUVHREFXCmdCUjhaSVBSQ0lJSjBwK3EwU0p1YWo4dGFtaFlHekFr
      QmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kwM09EZGkKTkdZNVptTmtMWHByYzNweE1JR0pCZ2dx
      QXdRRkJnY0lBUVI5ZXlKaGRIUnljeUk2ZXlKaFltRmpMbWx1YVhRaQpPaUowY25WbElpd2lZV1J0
      YVc0aU9pSjBjblZsSWl3aWFHWXVRV1ptYVd4cFlYUnBiMjRpT2lJaUxDSm9aaTVGCmJuSnZiR3h0
      Wlc1MFNVUWlPaUpCWkcxcGJrQnpkWEJ3YkhsamFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2kK
      WVdSdGFXNGlmWDB3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnU2hMWHVmbEJjdFZuM2plVklWZ1Yr
      cmNDVEhiQwpxd1laMjJWZVB2V2lJd0lDSUVBQm1hQUtYeEJ2ZmczWW5VMWlyTjFXN1k4Zk9ydS90
      ai9JSUhrZk9FWXAKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLUIOCgRTSEEyEgZTSEEyNTZKpQYt
      LS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ0pqQ0NBY3VnQXdJQkFnSUpBSnZFR0FTdlMw
      NG5NQW9HQ0NxR1NNNDlCQU1DTUhZeEN6QUpCZ05WQkFZVApBa2RDTVE4d0RRWURWUVFJREFaTWIy
      NWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIClQzSmtaWEpsY2pFek1E
      RUdBMVVFQXd3cVkyRXVjM1Z3Y0d4NVkyaGhhVzR0Ym1WMExtWmhZbkpwWTNSbGMzUXUKYUhsd1pY
      SnlibVF1WTI5dE1CNFhEVEl4TURnek1ERTBOVEF3TWxvWERUSTBNRFl4T1RFME5UQXdNbG93ZGpF
      TApNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5
      dVpHOXVNUkF3CkRnWURWUVFLREFkUGNtUmxjbVZ5TVRNd01RWURWUVFERENwallTNXpkWEJ3Ykhs
      amFHRnBiaTF1WlhRdVptRmkKY21samRHVnpkQzVvZVhCbGNuSnVaQzVqYjIwd1dUQVRCZ2NxaGtq
      T1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFTcwp6bHlHRDZKSzIzbEdoZHpHSW9laUR0MW1CVUFGRnVL
      aDlzU3BXNFZZbFNibzZhSlBGK0FxbGYzWjBxWDNkdkovCko0L1pxVjNtMG1idG9Bb2QveVAxbzBJ
      d1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQi93UUUKQXdJQnBqQWRCZ05WSFE0
      RUZnUVVmR1NEMFFpQ0NkS2ZxdEVpYm1vL0xXcG9XQnN3Q2dZSUtvWkl6ajBFQXdJRApTUUF3UmdJ
      aEFLVjl4Z2FFbmRZQkxlelErWmVUNXp6VEpXaTFSMEFyNmcrVFFNRFJWemtxQWlFQTBpMDgxcmZ6
      Cm1YQmhidkRKVGdTeFg3U3M3V2Q3d3R3dWhXb2lNeXdPVmJVPQotLS0tLUVORCBDRVJUSUZJQ0FU
      RS0tLS0tGgZBZG1pbnMiNwoHUmVhZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNo
      YWluTVNQGgZBZG1pbnMiNwoHV3JpdGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNo
      YWluTVNQGgZBZG1pbnMiOAoGQWRtaW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hh
      aW5NU1AQARoGQWRtaW5zIjsKC0VuZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3Vw
      cGx5Y2hhaW5NU1AaBkFkbWlucyoGQWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoG
      QWRtaW5zGh4KDEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0
      aW9ucxIIGgZBZG1pbnMaJAoMQ2FwYWJpbGl0aWVzEhQSCgoICgRWMl8wEgAaBkFkbWlucxqcNwoN
      Q29uc2Vuc3VzVHlwZRKKNxL/NgoIZXRjZHJhZnQS8jYKnxIKIG9yZGVyZXIxLmZhYnJpY3Rlc3Qu
      aHlwZXJybmQuY29tEPtBGvoILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQXNl
      Z0F3SUJBZ0lVVXJwUmo0MGNxR1B1UXAyRVBGbDlBcTE3VFFZd0NnWUlLb1pJemowRUF3SXcKZGpF
      TE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1
      Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNVE13TVFZRFZRUUREQ3BqWVM1emRYQndiSGxq
      YUdGcGJpMXVaWFF1ClptRmljbWxqZEdWemRDNW9lWEJsY25KdVpDNWpiMjB3SGhjTk1qRXdPRE13
      TVRRMU5EQXdXaGNOTWpJd09ETXcKTVRRMU9UQXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWJNQmtH
      QTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dQpaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5
      TVJBd0RnWURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFECkV4aHZjbVJsY21WeU1TNXpkWEJ3
      YkhsamFHRnBiaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUIKQndOQ0FBVGk3Tmhp
      dWx4bWVPWnJ6TGZJc1hoaWNEcTJndFg5M0duNDNMa2czcmJIWWkrQ1ZZcUVldEtxSlBvOQpNZkxl
      Y3FlTklXRkdJY0dKSVpwajhvRU5WWkxXbzRJQk5qQ0NBVEl3RGdZRFZSMFBBUUgvQkFRREFnT29N
      QjBHCkExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQU1CZ05WSFJNQkFmOEVB
      akFBTUIwR0ExVWQKRGdRV0JCUWNLYis5bW5Lc2dUVGdsU2VFWVlRZ3E5SHA4ekFmQmdOVkhTTUVH
      REFXZ0JSOFpJUFJDSUlKMHArcQowU0p1YWo4dGFtaFlHekJGQmdOVkhSRUVQakE4Z2hodmNtUmxj
      bVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFNDCklHOXlaR1Z5WlhJeExtWmhZbkpwWTNSbGMzUXVh
      SGx3WlhKeWJtUXVZMjl0TUd3R0NDb0RCQVVHQndnQkJHQjcKSW1GMGRISnpJanA3SW1obUxrRm1a
      bWxzYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaQpiM0prWlhKbGNqRXVj
      M1Z3Y0d4NVkyaGhhVzR0Ym1WMElpd2lhR1l1Vkhsd1pTSTZJbTl5WkdWeVpYSWlmWDB3CkNnWUlL
      b1pJemowRUF3SURTQUF3UlFJaEFObXZRdG5rc3Y3M056OGxaN01CTUtWcjYrVHgzdzZ0Q0xQM0tn
      VVQKZFFpVEFpQWR0emZ4UEdyQWZlZlFWdHJlSjd1QnlocnY5OXE2bjY4RnVVc2RqUTR1U1E9PQot
      LS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tIvoILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1J
      SURJVENDQXNlZ0F3SUJBZ0lVVXJwUmo0MGNxR1B1UXAyRVBGbDlBcTE3VFFZd0NnWUlLb1pJemow
      RUF3SXcKZGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFV
      RUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNVE13TVFZRFZRUUREQ3BqWVM1
      emRYQndiSGxqYUdGcGJpMXVaWFF1ClptRmljbWxqZEdWemRDNW9lWEJsY25KdVpDNWpiMjB3SGhj
      Tk1qRXdPRE13TVRRMU5EQXdXaGNOTWpJd09ETXcKTVRRMU9UQXdXakJ4TVFzd0NRWURWUVFHRXdK
      SFFqRWJNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dQpaRzl1TVJBd0RnWURWUVFLRXdk
      UGNtUmxjbVZ5TVJBd0RnWURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFECkV4aHZjbVJsY21W
      eU1TNXpkWEJ3YkhsamFHRnBiaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUIKQndO
      Q0FBVGk3TmhpdWx4bWVPWnJ6TGZJc1hoaWNEcTJndFg5M0duNDNMa2czcmJIWWkrQ1ZZcUVldEtx
      SlBvOQpNZkxlY3FlTklXRkdJY0dKSVpwajhvRU5WWkxXbzRJQk5qQ0NBVEl3RGdZRFZSMFBBUUgv
      QkFRREFnT29NQjBHCkExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQU1CZ05W
      SFJNQkFmOEVBakFBTUIwR0ExVWQKRGdRV0JCUWNLYis5bW5Lc2dUVGdsU2VFWVlRZ3E5SHA4ekFm
      QmdOVkhTTUVHREFXZ0JSOFpJUFJDSUlKMHArcQowU0p1YWo4dGFtaFlHekJGQmdOVkhSRUVQakE4
      Z2hodmNtUmxjbVZ5TVM1emRYQndiSGxqYUdGcGJpMXVaWFNDCklHOXlaR1Z5WlhJeExtWmhZbkpw
      WTNSbGMzUXVhSGx3WlhKeWJtUXVZMjl0TUd3R0NDb0RCQVVHQndnQkJHQjcKSW1GMGRISnpJanA3
      SW1obUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaQpiM0pr
      WlhKbGNqRXVjM1Z3Y0d4NVkyaGhhVzR0Ym1WMElpd2lhR1l1Vkhsd1pTSTZJbTl5WkdWeVpYSWlm
      WDB3CkNnWUlLb1pJemowRUF3SURTQUF3UlFJaEFObXZRdG5rc3Y3M056OGxaN01CTUtWcjYrVHgz
      dzZ0Q0xQM0tnVVQKZFFpVEFpQWR0emZ4UEdyQWZlZlFWdHJlSjd1QnlocnY5OXE2bjY4RnVVc2Rq
      UTR1U1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCpcSCiBvcmRlcmVyMi5mYWJyaWN0ZXN0
      Lmh5cGVycm5kLmNvbRD7QRr2CC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlESURDQ0Fz
      ZWdBd0lCQWdJVWZyUUZ6Z1BTRFkxZmd0RWFuZFRMbUpRU3FMa3dDZ1lJS29aSXpqMEVBd0l3CmRq
      RUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5
      dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVRNd01RWURWUVFERENwallTNXpkWEJ3Ykhs
      amFHRnBiaTF1WlhRdQpabUZpY21samRHVnpkQzVvZVhCbGNuSnVaQzVqYjIwd0hoY05NakV3T0RN
      d01UUTFOREF3V2hjTk1qSXdPRE13Ck1UUTFPVEF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViTUJr
      R0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXUKWkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21W
      eU1SQXdEZ1lEVlFRTEV3ZHZjbVJsY21WeU1TRXdId1lEVlFRRApFeGh2Y21SbGNtVnlNaTV6ZFhC
      d2JIbGphR0ZwYmkxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CCkJ3TkNBQVRibFdw
      RndQQkIwWmVTdmVHbzdqaDJZWjBCR3d6NFVwdzZybkRTK3libzV6WDRlRmQxd1hKOU1HVkoKUkZt
      M0xFNEtja2hqejVEUWtUbWJYbm9NNzNGaW80SUJOakNDQVRJd0RnWURWUjBQQVFIL0JBUURBZ09v
      TUIwRwpBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFNQmdOVkhSTUJBZjhF
      QWpBQU1CMEdBMVVkCkRnUVdCQlFCeG1TSmFybHoxWjQ1cUdUTFBDYjJFaUljL0RBZkJnTlZIU01F
      R0RBV2dCUjhaSVBSQ0lJSjBwK3EKMFNKdWFqOHRhbWhZR3pCRkJnTlZIUkVFUGpBOGdoaHZjbVJs
      Y21WeU1pNXpkWEJ3YkhsamFHRnBiaTF1WlhTQwpJRzl5WkdWeVpYSXlMbVpoWW5KcFkzUmxjM1F1
      YUhsd1pYSnlibVF1WTI5dE1Hd0dDQ29EQkFVR0J3Z0JCR0I3CkltRjBkSEp6SWpwN0ltaG1Ma0Zt
      Wm1sc2FXRjBhVzl1SWpvaUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2kKYjNKa1pYSmxjakl1
      YzNWd2NHeDVZMmhoYVc0dGJtVjBJaXdpYUdZdVZIbHdaU0k2SW05eVpHVnlaWElpZlgwdwpDZ1lJ
      S29aSXpqMEVBd0lEUndBd1JBSWdIckd0RzlURXhKcXBReFlHbTRSVjhXVWVraStkS1QrbWoyOEF3
      ZlBmCkZQY0NJSGIzcW1DVk5YK0taOXhhRUxXNlp0dy93cS9CV1BVOUY1M2FtcWJjNi9FdQotLS0t
      LUVORCBDRVJUSUZJQ0FURS0tLS0tIvYILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJ
      RENDQXNlZ0F3SUJBZ0lVZnJRRnpnUFNEWTFmZ3RFYW5kVExtSlFTcUxrd0NnWUlLb1pJemowRUF3
      SXcKZGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3
      d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNVE13TVFZRFZRUUREQ3BqWVM1emRY
      QndiSGxqYUdGcGJpMXVaWFF1ClptRmljbWxqZEdWemRDNW9lWEJsY25KdVpDNWpiMjB3SGhjTk1q
      RXdPRE13TVRRMU5EQXdXaGNOTWpJd09ETXcKTVRRMU9UQXdXakJ4TVFzd0NRWURWUVFHRXdKSFFq
      RWJNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dQpaRzl1TVJBd0RnWURWUVFLRXdkUGNt
      UmxjbVZ5TVJBd0RnWURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFECkV4aHZjbVJsY21WeU1p
      NXpkWEJ3YkhsamFHRnBiaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUIKQndOQ0FB
      VGJsV3BGd1BCQjBaZVN2ZUdvN2poMllaMEJHd3o0VXB3NnJuRFMreWJvNXpYNGVGZDF3WEo5TUdW
      SgpSRm0zTEU0S2NraGp6NURRa1RtYlhub003M0ZpbzRJQk5qQ0NBVEl3RGdZRFZSMFBBUUgvQkFR
      REFnT29NQjBHCkExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQU1CZ05WSFJN
      QkFmOEVBakFBTUIwR0ExVWQKRGdRV0JCUUJ4bVNKYXJsejFaNDVxR1RMUENiMkVpSWMvREFmQmdO
      VkhTTUVHREFXZ0JSOFpJUFJDSUlKMHArcQowU0p1YWo4dGFtaFlHekJGQmdOVkhSRUVQakE4Z2ho
      dmNtUmxjbVZ5TWk1emRYQndiSGxqYUdGcGJpMXVaWFNDCklHOXlaR1Z5WlhJeUxtWmhZbkpwWTNS
      bGMzUXVhSGx3WlhKeWJtUXVZMjl0TUd3R0NDb0RCQVVHQndnQkJHQjcKSW1GMGRISnpJanA3SW1o
      bUxrRm1abWxzYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaQpiM0prWlhK
      bGNqSXVjM1Z3Y0d4NVkyaGhhVzR0Ym1WMElpd2lhR1l1Vkhsd1pTSTZJbTl5WkdWeVpYSWlmWDB3
      CkNnWUlLb1pJemowRUF3SURSd0F3UkFJZ0hyR3RHOVRFeEpxcFF4WUdtNFJWOFdVZWtpK2RLVCtt
      ajI4QXdmUGYKRlBjQ0lIYjNxbUNWTlgrS1o5eGFFTFc2WnR3L3dxL0JXUFU5RjUzYW1xYmM2L0V1
      Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KnxIKIG9yZGVyZXIzLmZhYnJpY3Rlc3QuaHlwZXJy
      bmQuY29tEPtBGvoILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQXNlZ0F3SUJB
      Z0lVS2NnSnV2MG9WZms4bzB6ZWJDbDFPK1h4Z0Rnd0NnWUlLb1pJemowRUF3SXcKZGpFTE1Ba0dB
      MVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpN
      UkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNVE13TVFZRFZRUUREQ3BqWVM1emRYQndiSGxqYUdGcGJp
      MXVaWFF1ClptRmljbWxqZEdWemRDNW9lWEJsY25KdVpDNWpiMjB3SGhjTk1qRXdPRE13TVRRMU5E
      QXdXaGNOTWpJd09ETXcKTVRRMU9UQXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWJNQmtHQTFVRUJ4
      TVNOVEV1TlRBdkxUQXVNVE12VEc5dQpaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVJBd0Rn
      WURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFECkV4aHZjbVJsY21WeU15NXpkWEJ3YkhsamFH
      RnBiaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUIKQndOQ0FBUWFJb3BYUUpDaU53
      d3R5SE02MWFocDJMd0RsQ0JlQVRnU09lRWdoeFAzTlQvVW0yRlhVem01S1RHMgo3MVFzTzJXQVdP
      R3FMMjRweWhEY1pGNWJpRTJSbzRJQk5qQ0NBVEl3RGdZRFZSMFBBUUgvQkFRREFnT29NQjBHCkEx
      VWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWQKRGdRV0JCUW0xZ1hZa0xQTndDK1pBYmZmR0M0elVXNmwyREFmQmdOVkhTTUVHREFXZ0JS
      OFpJUFJDSUlKMHArcQowU0p1YWo4dGFtaFlHekJGQmdOVkhSRUVQakE4Z2hodmNtUmxjbVZ5TXk1
      emRYQndiSGxqYUdGcGJpMXVaWFNDCklHOXlaR1Z5WlhJekxtWmhZbkpwWTNSbGMzUXVhSGx3WlhK
      eWJtUXVZMjl0TUd3R0NDb0RCQVVHQndnQkJHQjcKSW1GMGRISnpJanA3SW1obUxrRm1abWxzYVdG
      MGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaQpiM0prWlhKbGNqTXVjM1Z3Y0d4
      NVkyaGhhVzR0Ym1WMElpd2lhR1l1Vkhsd1pTSTZJbTl5WkdWeVpYSWlmWDB3CkNnWUlLb1pJemow
      RUF3SURTQUF3UlFJaEFMQ1RyRjJETjlyVkRSRktSUEhxeHFJQzVYRTBQVHNNZEgyZkZzaGoKeWpo
      ekFpQjJ1VXBrRThTTmF1b3ArdDc3SHBGeHcwb0psWXY5YXpSQmFMSnNTUGExM3c9PQotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tIvoILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVEND
      QXNlZ0F3SUJBZ0lVS2NnSnV2MG9WZms4bzB6ZWJDbDFPK1h4Z0Rnd0NnWUlLb1pJemowRUF3SXcK
      ZGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNVE13TVFZRFZRUUREQ3BqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF1ClptRmljbWxqZEdWemRDNW9lWEJsY25KdVpDNWpiMjB3SGhjTk1qRXdP
      RE13TVRRMU5EQXdXaGNOTWpJd09ETXcKTVRRMU9UQXdXakJ4TVFzd0NRWURWUVFHRXdKSFFqRWJN
      QmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dQpaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxj
      bVZ5TVJBd0RnWURWUVFMRXdkdmNtUmxjbVZ5TVNFd0h3WURWUVFECkV4aHZjbVJsY21WeU15NXpk
      WEJ3YkhsamFHRnBiaTF1WlhRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUIKQndOQ0FBUWFJ
      b3BYUUpDaU53d3R5SE02MWFocDJMd0RsQ0JlQVRnU09lRWdoeFAzTlQvVW0yRlhVem01S1RHMgo3
      MVFzTzJXQVdPR3FMMjRweWhEY1pGNWJpRTJSbzRJQk5qQ0NBVEl3RGdZRFZSMFBBUUgvQkFRREFn
      T29NQjBHCkExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQU1CZ05WSFJNQkFm
      OEVBakFBTUIwR0ExVWQKRGdRV0JCUW0xZ1hZa0xQTndDK1pBYmZmR0M0elVXNmwyREFmQmdOVkhT
      TUVHREFXZ0JSOFpJUFJDSUlKMHArcQowU0p1YWo4dGFtaFlHekJGQmdOVkhSRUVQakE4Z2hodmNt
      UmxjbVZ5TXk1emRYQndiSGxqYUdGcGJpMXVaWFNDCklHOXlaR1Z5WlhJekxtWmhZbkpwWTNSbGMz
      UXVhSGx3WlhKeWJtUXVZMjl0TUd3R0NDb0RCQVVHQndnQkJHQjcKSW1GMGRISnpJanA3SW1obUxr
      Rm1abWxzYVdGMGFXOXVJam9pSWl3aWFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaQpiM0prWlhKbGNq
      TXVjM1Z3Y0d4NVkyaGhhVzR0Ym1WMElpd2lhR1l1Vkhsd1pTSTZJbTl5WkdWeVpYSWlmWDB3CkNn
      WUlLb1pJemowRUF3SURTQUF3UlFJaEFMQ1RyRjJETjlyVkRSRktSUEhxeHFJQzVYRTBQVHNNZEgy
      ZkZzaGoKeWpoekFpQjJ1VXBrRThTTmF1b3ArdDc3SHBGeHcwb0psWXY5YXpSQmFMSnNTUGExM3c9
      PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tEhIKBTUwMG1zEAoYASAFKICAgAgaBkFkbWlucyIq
      Cg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKB1JlYWRlcnMSFxIN
      CAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5z
      IiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zKgZBZG1pbnMSzgEKC0NvbnNvcnRp
      dW1zEr4BEnQKFVN1cHBseUNoYWluQ29uc29ydGl1bRJbGkAKFUNoYW5uZWxDcmVhdGlvblBvbGlj
      eRInEgwIAxIICgZBZG1pbnMaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zKhcvQ2hhbm5lbC9PcmRl
      cmVyL0FkbWlucyItCgZBZG1pbnMSIxIICAESBBICEgAaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5z
      KhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxomChBIYXNoaW5nQWxnb3JpdGhtEhISCAoGU0hBMjU2
      GgZBZG1pbnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI/////w8aBkFkbWlucxql
      AQoQT3JkZXJlckFkZHJlc3NlcxKQARJ1CiVvcmRlcmVyMS5mYWJyaWN0ZXN0Lmh5cGVycm5kLmNv
      bTo4NDQzCiVvcmRlcmVyMi5mYWJyaWN0ZXN0Lmh5cGVycm5kLmNvbTo4NDQzCiVvcmRlcmVyMy5m
      YWJyaWN0ZXN0Lmh5cGVycm5kLmNvbTo4NDQzGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxokCgxD
      YXBhYmlsaXRpZXMSFBIKCggKBFYyXzASABoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVh
      ZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFkbWlu
      cxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zKgZBZG1pbnMaDgoECgIKAAoACgAKAAoA
