apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: channel-mypeer-allchannel
  namespace: mypeer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: channel-mypeer-allchannel
  chart:
    git: https://github.com/balajihub/blockchain-automation-framework.git
    ref: main
    path: platforms/hyperledger-fabric/charts/create_channel   
  values:
    metadata:
      namespace: mypeer-net
      network:
        version 2.2.2
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.mypeer-net:7051
      localmspid: mypeerMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://acab3c720472246519b96cb01adcfe82-1250505999.us-east-2.elb.amazonaws.com
      authpath: dev2mypeer-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/mypeer-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/mypeer-net/orderer 
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel
    orderer:
      address: orderer1.supplychain-net:7050
    channeltx: |-
      Cq0DChgKFggCGgYIxPW6iQYiCmFsbGNoYW5uZWwSkAMKjQMKCmFsbGNoYW5uZWwSMBIeCgtBcHBs
      aWNhdGlvbhIPEg0KCW15cGVlck1TUBIAGg4KCkNvbnNvcnRpdW0SABrMAhKgAgoLQXBwbGljYXRp
      b24SkAIIARINCglteXBlZXJNU1ASABokCgxDYXBhYmlsaXRpZXMSFBIKCggKBFYyXzASABoGQWRt
      aW5zIiwKC0VuZG9yc2VtZW50Eh0SEwgDEg8KC0VuZG9yc2VtZW50EAIaBkFkbWlucyI1ChRMaWZl
      Y3ljbGVFbmRvcnNlbWVudBIdEhMIAxIPCgtFbmRvcnNlbWVudBACGgZBZG1pbnMiIgoHUmVhZGVy
      cxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZB
      ZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMqBkFkbWlucxonCgpDb25z
      b3J0aXVtEhkSFwoVU3VwcGx5Q2hhaW5Db25zb3J0aXVt
