apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: peer0-mypeer-cli
  namespace: mypeer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: peer0-mypeer-cli
  chart:
    git: https://github.com/balajihub/blockchain-automation-framework.git
    ref: main
    path: platforms/hyperledger-fabric/charts/fabric_cli    
  values:
    metadata:
      namespace: mypeer-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    storage:
      class: mypeersc
      size: 256Mi
    vault:
      role: vault-role
      address: http://a88bd27b6a15f42719b202bdfecef92c-869201622.us-east-2.elb.amazonaws.com
      authpath: dev2mypeer-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/mypeer-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/mypeer-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    peer:
      name: peer0
      localmspid: mypeerMSP
      tlsstatus: true
      address: peer0.mypeer-net:7051
    orderer:
      address: orderer1.supplychain-net:7050
